fastcampus/fastcomposer

package-lock.json
package.json

npm install --save-dev tar
npm audit fix
npm audit // found 0 vulnerabilities

hotfix: tar-update

---

package-lock.json
package.json

upgrade axios version for security vulnerability

---

package.json
src/components/editor/file-upload.vue
src/views/composer.vue

#40 이미지 업로드안되는 버그 수정
#27 편집창이 1000px이상인 경우 스크롤 표시
#44 저장버튼이 동작하지 않는 현상 수정

컴포저 저장 및 업로드가 동작하지 않는 현상 대응

---

package.json
src/components/common/modal.vue
src/main.js
src/views/composer.vue
src/views/index.js

#48 
* 전역으로 만드려고했으나 interface 구조상 다음 PR로 올리겠습니다.
* 저장시 안내팝업 표시 추가

모달팝업(저장시)추가

---

src/components/content/aside/aside.vue
src/components/content/aside/layer-basket/layer-basket.vue
src/components/content/aside/layouts/layouts.vue
src/components/content/preview/layer-content.vue
src/components/content/preview/preview.vue
src/components/header/header.vue
src/views/composer.vue

* 알림팝업 표시 개선 #55 
* vue life cycle을 이용한 함수사용과 선언 개선 #56

알림팝업 & vue 함수 선언 사용 및 개선

---

src/components/common/modal.vue
src/components/content/aside/aside.vue
src/components/content/aside/layers/layers.vue
src/components/content/aside/layouts/layouts.vue
src/components/content/preview/layer-content.vue
src/components/content/preview/preview.vue
src/components/editor/editor.vue
src/components/header/header.vue
src/views/composer.vue

composer css 스타일 사용개선

---

src/components/content/aside/layers/layers.vue
src/components/editor/file-upload.vue
src/views/composer.vue

* 선택레이어를 레이어 영역리스트에 표시한다.(#60 )
---추가사항---
* 레이어수정 패널이 aside영역아래로 내려가는 현상 수정, 최초 보이는 위치 수정(#53 )
* 이미지 업로드시 진행상태 표시 (#49 )
* 레이어 dnd시 선택 레이어 패널이 사라지는 문제 수정(#62)

layer 영역 부분개선

---

README.md

* vuejs에서 composer 사용을 위한 가이드를 README.md에 업데이트합니다.(#52 )

fastcomposer 가이드

---

src/components/content/aside/layers/layers.vue
src/components/content/aside/layouts/layouts.vue
src/views/composer.vue

* 레이어가 없는 경우 빈배열을 넘김(#64 )
* 선택레이어 클래스 사용 방식 변경

layer 데이터가 없을때 대응

---

package.json

컴포저 버전 업데이트 0.3.0

---

package.json

* 레이어 추가에 대한 사용성 개선
* 레이어 삭제 버그 수정
* 카운트 다운에대한 포맷 지원
* UI/UX 개선
* 기타 버그 사항 수정

v0.4.0 업데이트

---

package.json

컴포저 버전을 업데이트합니다.
https://github.com/fastcampusgit/fastcomposer/pull/83

chore: update v0.4.1

---

src/components/editor/editor.vue

raw html 입력을 위해 textarea를 추가합니다.

---

package.json

chore: update v0.4.2

---

src/components/content/preview/preview.vue

feat: move top save button

---

src/components/content/aside/layers/layers.vue
src/components/content/preview/layer-content.vue
src/components/editor/editor.vue
src/views/composer.vue

* 개발모드의 console 창에서 각 property가 존재하지 에러 수정합니다.
* 레이어 선택시 이동 에니메이션을 제거합니다.

fix bug in layer content and layers

---

src/components/editor/editor.vue
src/views/composer.vue

* layer 편집기 창 drag영역을 상단 이동 버튼에대해서만 적용합니다.

add draggable handle button

---

package.json

* 저장버튼 위치 변경합니다.
* prop가 존재하지는 않는 경우 layer content영역과 layers에서 발생하는 문제 수정합니다.
* 레이어 편집기를 버튼을 이용하여 이동하도록 변경합니다.

chore: update v0.4.3

---

src/components/content/preview/layer-content.vue

* 레이어 편집창에서 글자가 지워지지 않는 문제를 수정하였습니다.

fix bug at editor panel

---

package.json

chore: update v0.4.4

---

src/views/composer.vue

feat: fix max height limit value

---

package.json

chore: update v0.4.5

---

package.json

v0.5
- 레이어 편집채널 레이아웃 위치 변경합니다.
- 모달팝업을 지우고 토스트팝업이 추가됩니다.(모달팝업은 추후 다시 적용 예정)
- 저장된 시간 표시

chore: update v0.5.0

---

src/components/common/message-toast.vue
src/components/content/aside/aside.vue
src/components/content/layouts/layouts.vue
src/components/content/preview/layer-content.vue
src/components/content/preview/preview.vue
src/components/editor/editor.vue
src/components/editor/file-upload.vue
src/components/header/header.vue
src/utils/utils.js
src/views/composer.vue

fix fastcomposer prefix

---

src/components/common/modal.vue
src/components/header/header.vue
src/views/composer.vue

add tag guide

---

package.json

* textarea에서 사용되는 tag도움말이 추가되었습니다.
* 선택레이어가 미리보기에서 표시됩니다.

chore: update v0.7.0

---

package.json
src/renderer/index.js
test/renderer/renderer.spec.js
webpack.config.test.js

레이아웃 디자인 변경시 전체 페이지 갱신에 사용할 render 함수를 간단히 만들었습니다.

add headless renderer

---

src/components/content/preview/layer-content.vue

editor에서 변경해도 preview에 즉시 반영되지 않는 버그 수정.
선 머지 후 개선.

fix preview live update

---

src/components/editor/editor.vue
src/views/composer.vue

Fix focus bug when selected layout

---

src/views/composer.vue

알수 없는 이유로... ctrl+shift+0 키조합에 keypress 이벤트가 발생하지 않음

Change shortcut ctrl+shift to alt+shift

---

package.json

misc: update dependcies

---

src/components/content/preview/preview.vue

* 레이아웃 저장시 layout value의 prop기준으로 layer value prop를 동기화 합니다.

synchronize props for layer values based layout values

---

src/components/content/aside/layers/layers.vue
src/components/content/preview/layer-content.vue
src/views/composer.vue

* 추가된 레이어를 show/hide가 가능하도록 복원합니다.

revert layer show/hide

---

src/components/content/aside/layers/layers.vue
src/components/content/layouts/layouts.vue
src/components/header/header.vue
src/views/composer.vue

add favorite layout

---

package.json

* 레이어 복제기능 추가
* 레이아웃 즐겨찾기 추가
* 기타 버그사항 수정

chore: update v0.8.0

---

src/views/composer.vue

* 레이어를 복제 후 복제된 레이어가 선택되도록 합니다.

fix focus movement to cloned layer after layer clone

---

package.json

chore: update v0.8.1

---

src/components/common/tooltip.vue
src/components/editor/editor.vue
src/views/composer.vue

컴포저에 툴팁기능이 추가됩니다.
layout.json파일에서 description의 값으로 채워지도록 하였습니다.

add tooltip(V2-114)

---

package.json

* 저장시 나타나는 안내 메세지 버그 수정
* 툴팁 기능 추가
* 레이어 미리보기와 레이어 리스트 동기화
* 레이어 dnd 후 drop된 레이어로 index이동

chore: update v0.9.0

---

src/components/header/header.vue
src/views/composer.vue

add layer count

---

package.json

* 툴팁 버그를 해결합니다.
* 레이아웃 패널위치가 정확하게 위치되도록합니다.
* 레이어카운트가 추가됩니다.

chore: update v0.9.1

---

src/components/content/aside/layers/layers.vue
src/components/header/header.vue
src/views/composer.vue

* 제목이나 본문에 tag가 열거, 닫힘태그가 서로 일치하지 않으면 레이어에 표시하도록 표시합니다.

add validate layer

---

package.json

chore: update v0.10.0

---

src/components/content/aside/layers/layers.vue
src/components/header/header.vue
src/views/composer.vue

* 점검 할 레이어 카운트 추가
* value가 불린값으로 들어가는경우 정상적으로 동작하지 않았던 문제 수정

Fix validate checker

---

package.json

chore: update v0.10.1

---

src/components/editor/editor.vue
src/components/editor/file-upload.vue

* 비디오를 업로드를 가능하도록 타입이 추가됩니다.
* 컴포저로 업로드시 파일 사이즈를 제한하여 경고합니다.
* 이미지: 2MB
* 비디오(mp4): 5MB

add upload limit

---

package.json

chore: update v0.11

---

src/components/editor/file-upload.vue

* 이미지업로드시 500kb 이상 업로드시 경고창을 보여줍니다.

fix image upload limit size

---

package.json

* 이미지 업로드시 500kb 이상 업로드시 경고창을 보여줍니다.

chore: update v0.11.1

---

package.json

0.11.1 버전이 잘못업데이트되어 0.11.2로 다시 올립니다.

chore: 버전 0.11.2

---

src/components/content/aside/aside.vue
src/components/content/aside/layers/layers.vue
src/utils/utils.js
src/views/composer.vue

사업부 요청사항으로 레이어를 여러개 이동 하도록 개선합니다.
단축어

레이어 다중 선택하여 정렬이 가능하도록 추가

---

package.json

chore: 0.12.0

---

layouts/index.js
layouts/list/icon.svg
layouts/list/index.js
layouts/list/layout.json
layouts/list/style.scss
layouts/list/template.ejs
layouts/sample.json
src/components/content/aside/aside.vue
src/components/editor/editor.vue
src/components/editor/file-upload.vue
src/views/composer.vue

다음기능이 추가됩니다.
1. 레이아웃에서 특정 포맷에 따라 layouts.json을 생성하면 요소를 추가 삭제가 가능합니다.
2. limit을 추가하여 최대 추가를 정의할 수 있습니다.
3. 사용 가이드는 별도 문서로 README.md에 업데이트 예정.

콘텐츠를 추가/삭제 가능하도록 input type을 추가합니다(V2-591)

---

README.md

콘텐츠 추가/삭제 관련해서 README파일이 업데이트됩니다.

콘텐츠 추가/삭제 관련 README업데이트

---

package.json

#180 
* 레이아웃의 콘텐츠 요소 추가/삭제 기능이 추가됩니다.
* readme.md에 신규 레이아웃 포맷 인터페이스 설명이 업데이트됩니다.

chore: 0.13.1

---

src/components/editor/editor.vue
src/views/composer.vue

리스트 형의 요소에서 select type옵션을 추가합니다.

리스트형의 요소에서 select type 대응

---

package.json

chore: 0.13.2

---

layouts/list/layout.json
src/components/editor/editor.vue

레이아웃에서 요소 추가하는 경우 기본값을 설정 가능하도록합니다.

레이아웃 요소추가,삭제 기본값 적용

---

layouts/list/layout.json
src/components/editor/editor.vue

레이어 에디터 편집기에서 필수 옵션을 추가합니다.(저장 시 동작로직은 추후 추가 예정)

속성에 필수옵션을 표시 할 수 있도록 추가

---

src/components/editor/editor.vue

편집 요소 추가 버튼 디자인 개선

---

src/components/editor/editor.vue

추가/삭제 요소의 속성명에 구분선을 추가

---

package.json

* 요소 추가 삭제 속성명 구분 선 추가
* package 업데이트
* 편집요소 추가 버튼 디자인 개선
* 편집요소 요소 추가 기본값 적용

컴포저 버전 0.14.0

---

src/components/editor/editor.vue

스크린샷과 같이 cards 내 카드 요소에도 툴팁을 적용합니다.

cards 의 카드 요소에 툴팁 추가

---

package.json

- cards 의 카드 요소에 툴팁 추가
- 컴포저 편집창에서 요소 사이의 border색상을 변경(V2-1022)

컴포저 버전 v0.14.2

---

package.json

package 정보 업데이트

---

README.md

version badge를 추가

---

.github/workflows/fastcomposer-test.yml
ci_test.sh
package.json

Unit Test
E2E Test
자동으로 돌 수 있게 구성합니다.

Github Actions 을 추가합니다. 

---

package.json

컴포저 버전을 0.15.0 업데이트
- 디바이스 미리보기 추가(desktop, tablet, mobile)
-  컴포저 컴포넌트 구조 개선
- moment 제거
- cypress 적용

version 0.15.0

---

package.json
src/views/composer.vue

이미지 업로드를 시도하는 경우 callback이 동작하지 않는 문제를 수정합니다.(V2-2448)

파일 업로드 문제 수정 (V2-2448)

---

package.json
src/views/editor/editor.vue

레이어가 선택이되면 기존값이 초기화되는 문제가 수정되었습니다.

레이어 선택 오류 수정

---

package.json
src/views/composer.vue

버그수정
https://fastcampus.atlassian.net/browse/V2-2521
layer list container 하단에 공간을 추가하는 style 
아니요~
local, smoke test

fix: 하단에 추가되는 레이어인스턴스에 리스트요소가 가려지지 않게 처리(V2-2521)

---

README.md
cypress/integration/composer/composer_spec.js
package.json
src/views/composer.vue
src/views/editor/editor.vue

[X] 버그 수정
https://fastcampus.atlassian.net/browse/V2-2936
이미 사용중인 layer 에 새로운 옵션추가시 해당 레이어를 포함해 작성된 페이지 저장시 추가된 옵션이 동기화되지 않아 오류 발생되어 저장 오류 발생
v2 의 module 에서 테스트 후 완료된 코드 옮김
local, smoke test

Fix/sync params ( V2-2936 )
